### ISSUE TITLE
Check if admin route has a checker

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#106]
## User story
1. As a normal user
2. I want / need my data to really only be visible to the admins of my company
3. So that my data is protected

## Acceptance criteria
* User and resource management pages are really only visible for admins
* If people try to manually reach the admin routes, they are redirected to a user page

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by n3rdc4ptn** [comment]
Done, already working
