### ISSUE TITLE
Git Commit Pipeline

### ISSUE THREAD

**Issue by Ardianpalloshi** [amosproj/amos2022ws05-shared-desk-mgmt#12]
## User story
1. As a software developer
2. I want / need a git commit pipeline with automated tests
3. So that no buggy code gets added to the main development branch

## Acceptance criteria
* [x] Code commited to the main branch is only integrated into the existing solution if all tests are passed
* [x] Automated tests are added to ensure a certain code quality
* [x] Commit pipeline outputs code coverage for easier checking of sprint release DoD

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by stefanpfahler** [comment]
Current test coverage:

|Filename                    |   Stmts  |  Miss  |Cover  | Missing|
|----------------------------|----------|--------|-------|------------|
|Program.cs                  |      54  |    54  |0.00%  | 11-79|
|EnumSchemaFilter.cs         |      19  |    19  |0.00%  | 11-29|
|Usecases\AuthUsecases.cs    |      98  |     2  |97.95% | 61-62|
|Usecases\BookingUsecases.cs |      39  |     0  |100.00%||
|Models\CreateTokenUser.cs   |       2  |     2  |0.00%  | 8-11|
|Models\LoginResponse.cs     |       1  |     0  |100.00%||
|Models\RecentBooking.cs     |       7  |     0  |100.00%||
|Models\RegisterResponse.cs  |       1  |     0  |100.00%||
|Models\RegisterUser.cs      |       5  |     0  |100.00%||
|Entities\Booking.cs         |       8  |     0  |100.00%||
|Entities\Building.cs        |      10  |     0  |100.00%||
|Entities\Company.cs         |      15  |     1  |93.33% | 17|
|Entities\Desk.cs            |      11  |     0  |100.00%||
|Entities\DeskType.cs        |       9  |     0  |100.00%||
|Entities\Floor.cs           |       9  |     0  |100.00%||
|Entities\Role.cs            |       9  |     9  |0.00%  | 13-19, 8-11|
|Entities\Room.cs            |       9  |     0  |100.00%||
|Entities\User.cs            |      17  |     0  |100.00%||
|DataAccess\DataContext.cs   |     230  |     3  |98.69% | 14-16|
|Core\constants.cs           |       8  |     8  |0.00%  | 5-13|
|TOTAL                       |     561  |    98  |82.53% ||
