### ISSUE TITLE
Personal Desk Booking Page - UI

### ISSUE THREAD

**Issue by Ardianpalloshi** [amosproj/amos2022ws05-shared-desk-mgmt#14]
## User story
1. As a user
2. I want / need to see a UI page for booking personal desks
3. So that I can select a date and time as well as select my desk preferences

## Acceptance criteria
* The UI page for booking personal desks should show the text: Hello username, book a personal desk
* The page should provide a calendar to select a date and an option to enter a time for booking desks
* The page should offer options to select preferences specified by the company (drop down menues, use mock data): location, building, room, desk type
* The page should show a search button to initialize the booking search process
* Only frontend

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by qy21gafy** [comment]
The page should be available through a seperate entry in the top bar.

**Comment by xilef45** [comment]
add react-datepicker to bill of material

**Comment by qy21gafy** [comment]
Is this currently set up to have a start date+time and end date+time or only one date+time?

**Comment by xilef45** [comment]
@qy21gafy We can do that both, we'd implement a start and end time if that is correct.
