### ISSUE TITLE
Error in Input Component

### ISSUE THREAD

**Issue by xilef45** [amosproj/amos2022ws05-shared-desk-mgmt#158]
**Describe the bug**
The Name isn't shown, otherwise the placeholder is shown in Input Component
**To Reproduce**
1. Go to (http://localhost:3000/users)
2. Click on edit of one user

**Expected behavior**
The Name isn't shown, otherwise the placeholder is shown.

**Screenshots**
![Fehler2](https://user-images.githubusercontent.com/88111260/212398212-301976df-632c-4cca-8057-fe0a85bff6a5.PNG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by stefanpfahler** [comment]
So the bug is that the current user information is only shown as a placeholder instead of being "real" text?

**Comment by n3rdc4ptn** [comment]
Done


will be closed by #151
