### ISSUE TITLE
Resource Booking - UI

### ISSUE THREAD

**Issue by Ardianpalloshi** [amosproj/amos2022ws05-shared-desk-mgmt#16]
## User story
1. As a user
2. I want / need to be able to see a page to book one of the available desks returned from the search function
3. So that it is reserved for me and I can use it

## Acceptance criteria
* UI page should be show the text: "Search Results:"
* UI should use drop down menus to display results sorted hierarchically by location->building->room (e.g by unfolding content)
* UI page should display results in a table
* UI page should display properties and names of all available resources
* UI page should offer a book button next to each result
* UI page should show an example with mock data

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by eddyhakimi** [comment]
@Ardianpalloshi , what do you mean with location?
The actual address or just the city/country of the building?
The database currently contains only the building addresses for building locations, which result in an 1:1 relationship between them. 
More specifically, each location collapse would contain only one building collapse.

Should I implement building->floor->room instead?
