### ISSUE TITLE
Time issue book a desk-> bookings

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#190]
**Describe the bug**
The booking time displayed in bookings lies 1h before the time selected in book a desk. This does not happen when using the edit bookings function. This happens when using the production server.

**To Reproduce**
1. Go to book a desk
2. Book a desk, remember the time
3. Look at the booking in Bookings

**Expected behavior**
The times should be the same

**Screenshots**
![image](https://user-images.githubusercontent.com/115994315/215035959-4e2daa7f-ae50-42d7-9c5b-dda936a1b45d.png)
![image](https://user-images.githubusercontent.com/115994315/215035972-ba3688af-1d00-4907-a9dd-0e3fd5616a6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by n3rdc4ptn** [comment]
THis is a display error in the My Bookings Overview, i will fix that this sprint.
