### ISSUE TITLE
Resource overview does not update when resource is added

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#195]
**Describe the bug**

**To Reproduce**
1. Go to resource overview
2. Display all desks
3. Add a new desk
4. It doesn't appear in the overview :(

**Expected behavior**
The new desk should appear in the list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jantiegges** [comment]
As the amount of work necessary for properly resolving this issue would have exceeded an 8, this issue is tackled by the workaround of just reloading the page in case of an updated resource

**Comment by n3rdc4ptn** [comment]
https://github.com/amosproj/amos2022ws05-shared-desk-mgmt/issues/195#issuecomment-1419719535
Because the frontend needs a lot of refactoring in the resources index page. The whole page needs to be restructured and seperated into multiple files for easiert development and better User Experience.
