### ISSUE TITLE
Connect FE and BE for login and registration function

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#38]
## User story
1. As a user
2. I want / need the login and registration function in the UI to actually check the inputed data
3. So that the login and registration works correctly and doesn't just allow anyone onto the system

## Acceptance criteria
* Frontend and backend get connected for login and registration function
* Login and registration functions display error message when they fail
* Registration function displays a message when it succeeds
* Backend adds error functions

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by n3rdc4ptn** [comment]
Register Errors:
```json
{
	"error": "MailAddressAlreadyExists",
	"msg": "Mail address already exists"
}
```

```json
{
	"error": "CompanyNotExists",
	"msg": "Company does not exist"
}
```

Login Errors:
```json
{
     "error": "UserNotAccepted",
     "msg": "User is not accepted"
}
```

```json
{
     "error": "WrongCredentials",
     "msg": "Wrong credentials typed in"
}
```

**Comment by n3rdc4ptn** [comment]
Optional:
/auth/me --> get user information

**Comment by xilef45** [comment]
now the endpoint should produce fitting errormessages
