### ISSUE TITLE
Docker compose backend

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#39]
## User story
1. As a software developer
2. I want / need the docker compose to work correctly with the backend
3. So that it's easier to run our system

## Acceptance criteria
* [x] Docker compose works correctly with backend

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by n3rdc4ptn** [comment]
Work on a devcontainer implementation for easier development working

**Comment by n3rdc4ptn** [comment]
@woerndle @stefanpfahler we can talk about the devcontainer implementation. Maybe this solves this item already or you only need to extend it a bit.
