### ISSUE TITLE
Connect FE an BE for recent bookings on overview page and booking overview

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#41]
## User story
1. As a user
2. I want / need to see the correct recent and future bookings for myself stored in the database
3. So that I am reminded which desks I booked 

## Acceptance criteria
* Mock data in FE gets replaced with real data queried from the backend 
* For the overview front page the bookings for the current day and all upcoming bookings are shown
* For the bookings overview page all bookings should be shown

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by n3rdc4ptn** [comment]
@woerndle Can we have another information when getting a list of bookings in the bookings route?
Like:
```json
{
  "total": 20,
  "bookings": [...normal Bookings return]
}
```
