### ISSUE TITLE
Booking Overview Backend

### ISSUE THREAD

**Issue by qy21gafy** [amosproj/amos2022ws05-shared-desk-mgmt#50]
## User story
1. As a user
2. I want / need to see my future bookings in the system on my bookings page
3. So that I know which desks I have booked

## Acceptance criteria
* Implement end point that gives back all bookings of the current user depending on input
* The function should return the booked desks together with their name, location, building, room, date and time details

## Definition of done (DoD)
* The code has been peer-reviewed by at least one team member
* The documentation was updated if necessary
* The bill of materials was updated if necessary
* Working dev setup was created

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by qy21gafy** [comment]
Developers should discuss the input so that bookings in a certain time range and a certain amount of bookings can be returned.

**Comment by n3rdc4ptn** [comment]
## Booking Overview Backend

Parameters:
```
n -> Amount of Bookings
skip -> Amount of Bookings we want to skip
direction / sort -> Sort direction depending on the start time of the bookings
from -> from that time (when not specified, everything until the end time)
end -> end or until this the bookings (when not specified, infinite into future)
```

can be easy put into a sql query (dont know how ORM does it)
```sql
PSEUDO CODE

SELECT *
FROM table
WHERE $from < item.start
ORDER BY item.start $direction
LIMIT $n
OFFSET $skip
```

Examples:
```
/bookings?n=100 - Get 100 Bookings
/bookings?skip=10&n=10 - Get 10 Bookings after the first 10 Bookings skipped
```
