### ISSUE TITLE
Overview Page UI

### ISSUE THREAD

**Issue by Ardianpalloshi** [amosproj/amos2022ws05-shared-desk-mgmt#8]
## User story

1. As a user
2. I want / need to see an overview page after logging in
3. So that I know I successfully logged in and can now book desks

## Acceptance criteria

- The page should be the first page seen after logging in
- The page should show the text: "Hello username, welcome back to Deskstar"
- The page should provide a brief overview over the most recent bookings ( mock data )
- The page should contain a button that runs the logout function

## Definition of done (DoD)

- The code has been peer-reviewed by at least one team member
- The documentation was updated if necessary
- The bill of materials was updated if necessary
- Working dev setup was created

## DoD general criteria

- Feature has been fully implemented
- Feature has been merged into the mainline
- All acceptance criteria were met
- Product owner approved features
- All tests are passing
- Developers agreed to release

**Comment by jantiegges** [comment]
short-term a list view is probably fine, but maybe we can already have a look at a calendar view like this: [Week view](https://tailwindui.com/components/application-ui/data-display/calendars#component-89f285aeebb60ddecb7ec8b5e664d525)

**Comment by qy21gafy** [comment]
The list view of most recent bookings should contain the 10 most recent bookings including the desk name, building, room, date and time.
